export { DashboardPage } from './DashboardPage'
export { CoursesPage } from './CoursesPage'
export { SubmissionsPage } from './SubmissionsPage'
export { CompletedPage } from './CompletedPage'
export { CEBrokerPipelinePage } from './CEBrokerPipelinePage'
export { LogsPage } from './LogsPage'
export { SettingsPage } from './SettingsPage'
